Mathjax and responsive case
eol-uchile/eol-container-xblock pull request #15
Opened 2024-04-03 15:07 UTC by Lozamded

Se agrego compatibilad con latex por medio de la biblioteca mathjax ademas se agregaron funcionalidades responsivas para las tablas

2024-04-15 18:45 UTC, tomaspemora commented
En el primer commit se elimina la función responsiva y en el segundo se agrega. Sugiero hacer un rebase y sacar así anular esa parte del PR. Además, sugiero implementar la integración con Mathjax a nivel del tema. Añadir tantas veces como bloques tenga la página es ineficiente.

2024-04-23 14:10 UTC, tomaspemora requested changes
En el primer commit se elimina la función responsiva y en el segundo se agrega. Sugiero hacer un squash y anular esa parte del PR. Además, sugiero implementar la integración con Mathjax a nivel del tema. Añadir tantas veces como bloques tenga la página es ineficiente.

2024-05-06 21:34 UTC, Lozamded commented
Se cambio la forma en que se recarga el mathjax y en conjunto a capsulas nuevas, todo esto se squasheo a un solo commit.

2024-05-07 13:16 UTC, fsologureng requested changes
Cambios menores para minimizar afectación de código.

2024-05-07 13:16 UTC, fsologureng commented on eolcontainer/eolcontainer.py
> +
Linea en blanco de más. Cambio innecesario.

2024-05-07 13:16 UTC, fsologureng commented on eolcontainer/eolcontainer.py
> +    editable_fields = ('type', 'text', 'case_title', 'show_header', 'show_footer','responsive','background_color_header','background_color_icon','border_color','icon_url')
Ideal sería dejarlos todos con coma (,) y espacio o todos sin espacio entre las comas.

2024-05-07 13:16 UTC, fsologureng commented on eolcontainer/static/html/eolcontainer.html
> +
Linea en blanco de sobra. Cambio innecesario.

2024-05-07 21:13 UTC, Lozamded commented
Se aplicaron los cambios solicitados en cuanto a espacios o lineas innecesarias

2024-05-07 21:38 UTC, fsologureng approved these changes

2024-05-07 21:48 UTC, fsologureng commented
@Lozamded: puedes hacer git pull con rebase de master, por favor? para actualizar el workflow de testing...

2024-05-07 21:48 UTC, tomaspemora approved these changes

2024-05-07 22:38 UTC, Lozamded commented
Listo ¿Es necesario squashearlo?

2024-05-07 23:11 UTC, fsologureng commented
> Listo ¿Es necesario squashearlo?

qué comandos ejecutaste? no quedó bien, más parece un merge que un rebase...

2024-05-08 14:44 UTC, Lozamded commented
Si me confundi  e hice un merge, volvere atras para hacerlo como rebase

2024-05-08 16:51 UTC, merged